export const CONSTANTS = {
  ADD_CARD: "ADD_CARD",
  REMOVE_CARD: "REMOVE_CARD",
  ADD_LIST: "ADD_LIST",
  DRAG_HAPPENED: "DRAG_HAPPENED",
  GET_FARMS: "GET_FARMS",
  SELECT_FARMERS: "SELECT_FARMERS",
  UNSELECT_FARMERS: "UNSELECT_FARMERS",
  REGISTRATION: "REGISTRATION",
  COMPLETE_ORDER: "COMPLETE_ORDER"
};
